sudo: required

language: python

python:
  - "3.5"

services:
  - docker

before_script:
  - docker-compose -f docker-compose.yml -f docker-compose.ci.yml build

script:
  - docker run -it cvat_ci /bin/bash -c 'python3 manage.py test cvat/apps utils/cli'
  - docker run -it cvat_ci /bin/bash -c 'python3 manage.py test datumaro/'
  - docker run -it cvat_ci /bin/bash -c 'cd cvat-core && npm install && npm run test && npm run coveralls'
